services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kodem_cards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  firebase-emulators:
    build:
      context: .
      dockerfile: dockerfiles/firebase.Dockerfile
    container_name: firebase-tools
    ports:
      - "9099:9099" # Auth Emulator
      - "4000:4000" # Emulator UI

volumes:
  postgres_data:
  redis_data:
